services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app_net
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password



networks:
  app_net:
    driver: bridge

volumes:
  db_data:
    driver: local