version: '3.8'  # Especifica la versión del Compose file (recomendado)

services:
  app:
    image: my-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app_net
    ports:
      - "5432:5432"
    restart: always

networks:
  app_net:
    driver: bridge


