version: '3.8'

services:
  custom_db:
    image: postgres:14
    environment:
      POSTGRES_DB: custom_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app_net
    restart: unless-stopped
    volumes:
      - custom_db_data:/var/lib/postgresql/data

  custom_app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - custom_db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://custom_db:5432/custom_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

networks:
  app_net:
    driver: bridge

volumes:
  custom_db_data:
    driver: local
