services:
  app:
    image: my-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app_net
    ports:
      - "5432:5432"

networks:
  app_net:
    driver: bridge