package com.laberit.sina.bootcamp.modulo5.mini_sina_by_cesar.model.enumerations;

public enum Permission {
    MANAGE_USERS,
    VIEW_PATIENTS,
    MANAGE_DIAGNOSIS,
    MANAGE_APPOINTMENTS,
    VIEW_ANALYTICS,
    CREATE_APPOINTMENTS,
    CANCEL_OWN_APPOINTMENT,
    CREATE_PATIENT_APPOINTMENT,
    UPDATE_APPOINTMENT_STATUS,
    VIEW_DIAGNOSIS,
    VIEW_OWN_APPOINTMENTS
}